name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        run: rm -rf /github/workspace/.git/
    
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.deploy }}
          PUBLISH_REPOSITORY: oimasterakioi/blog
          BRANCH: master
          PUBLISH_DIR: ./
